[nas]
vmdeb-nas.teleranger.xyz ansible_user=simon

[debian_guest]
192.168.247.38 ansible_user=simon

[proxmox]
192.168.247.25 ansible_user=simon

[dietpi]
192.168.247.10 ansible_user=dietpi

[workstation]
localhost ansible_connection=local ansible_user=simon