---

- name: Create directory for ansible facts
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d

- name: Copy fact template
  template:
    src: ../templates/firmware.j2
    dest: /etc/ansible/facts.d/firmware.fact
    force: False

- name: Re-read facts after adding custom fact
  ansible.builtin.setup:
    filter: ansible_local

- name: Copy modprobe config
  template:
    src: ../templates/i915.j2
    dest: /etc/modprobe.d/i915.conf
  notify: Update initramfs

- name: load ip6_table module
  community.general.modprobe:
    name: ip6_tables
    persistent: present

- name: Install prerequisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - nfs-common
      - git
      - qemu-guest-agent
      - rsync
    state: latest
    update_cache: true

- name: Add i915 firmware 
  block:
    - name: Download & extract firmware tarball
      ansible.builtin.unarchive:
        src: "https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/{{ firmware_version }}.tar.gz"
        dest: "/home/{{ ansible_user }}"
        remote_src: yes
    - name: Copy i915 firmware
      ansible.builtin.copy:
          src: "/home/{{ ansible_user }}/{{ firmware_version }}/i915"
          dest: "/lib/firmware"
          owner: root
          group: root
          remote_src: yes
      notify: Update initramfs
    - name: Update firmware facts
      community.general.ini_file:
        path: /etc/ansible/facts.d/firmware.fact
        section: info
        option: version
        value: "{{ firmware_version }}"
  always:
    - name: Cleanup 
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/{{ firmware_version }}"
        state: absent
  when: ansible_local['firmware']['info']['version'] != firmware_version

- name: Enable qemu guest agent service
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Adding user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Stat mountpoint
  stat:
    path: "{{ nfs_mountpoint }}"
  register: mp_stat

- name: Create mountpoint
  ansible.builtin.file:
    path: "{{ nfs_mountpoint }}"
    state: directory
    mode: 0666
    owner: root
    group: users
  when: not mp_stat.stat.exists

- name: Mount network share
  ansible.posix.mount:
    src: "{{ nfs_location }}"
    path: "{{ nfs_mountpoint }}"
    fstype: nfs
    opts: "rw,auto,hard,intr,rsize=8192,wsize=8192,timeo=14"
    state: mounted

- name: Generate SSH key 
  openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: ed25519
    state: present
  become: False

- name: Check SSH public key   
  command: /bin/cat /home/{{ ansible_user }}/.ssh/id_ed25519.pub
  register: cat
  changed_when: False

- name: Print SSH public key
  debug: var=cat.stdout

- name: Wait for user to copy SSH public key   
  pause: prompt="Please add the SSH public key above to your GitHub account"

- name: Checkout services repo
  become: False
  git:
    repo: "{{ services_repo }}"
    dest: "/home/{{ ansible_user }}/docker-stuff"
    accept_newhostkey: true