- name: Debian Provisioner
  hosts: debian-guest
  become: true
  roles:
    - role: ../../roles/provision_guest
    - role: ../../roles/crypttab
      vars: 
        luks_key: ../../luks-keys/scratch
        mountpoint: /scratch
        luks_device_id: 9e9f39a4-216e-4dbe-aae4-d2089c2e017a
        mount: true