- name: Debian Provisioner
  hosts: debian-guest
  become: true
  roles:
    - role: ../../roles/unattended_upgrades
      vars:
        unattended_upgrades_origins:
          - '"origin=*";'
        unattended_upgrades_automatic_reboot: true
    - role: ../../roles/install_i915_firmware
    - role: ../../roles/install_guest_agent
    - role: ../../roles/install_docker
    - role: ../../roles/mount_nfs
    - role: ../../roles/nfs_share
      vars:
        nfs_share_src: /scratch
        nfs_share_export: /export/scratch
        nfs_share_allowed_ips:
          - 192.168.247.126
    - role: ../../roles/add_docker_repo
    # - role: ../../roles/crypttab
    #   vars: 
    #     luks_key: ../../luks-keys/scratch
    #     mountpoint: /scratch
    #     luks_device_id: 9e9f39a4-216e-4dbe-aae4-d2089c2e017a
    #     mount: true