---

- name: Look up docker_compose_user's uid and home dir
  ansible.builtin.getent:
    database: passwd
    key: "{{ docker_compose_user }}"

- name: Ensure user systemd dir exists
  become: "{{ docker_compose_user != ansible_user }}"
  become_user: "{{ docker_compose_user }}"
  ansible.builtin.file:
    path: "{{ ansible_facts.getent_passwd[docker_compose_user][4] }}/.config/systemd/user"
    state: directory
    mode: '0755'

- name: Copy docker compose up systemd service
  become: "{{ docker_compose_user != ansible_user }}"
  become_user: "{{ docker_compose_user }}"
  ansible.builtin.template:
    src: docker-compose-up.service.j2
    dest: "{{ ansible_facts.getent_passwd[docker_compose_user][4] }}/.config/systemd/user/{{ docker_compose_service_name }}.service"
    mode: '0644'

- name: Copy docker compose up systemd timer
  become: "{{ docker_compose_user != ansible_user }}"
  become_user: "{{ docker_compose_user }}"
  ansible.builtin.template:
    src: docker-compose-up.timer.j2
    dest: "{{ ansible_facts.getent_passwd[docker_compose_user][4] }}/.config/systemd/user/{{ docker_compose_service_name }}.timer"
    mode: '0644'

- name: Check linger status for docker_compose_user
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ docker_compose_user }}"
  register: docker_compose_linger

- name: Enable linger for docker_compose_user
  ansible.builtin.command: "loginctl enable-linger {{ docker_compose_user }}"
  when: not docker_compose_linger.stat.exists

- name: Enable and start docker compose up timer
  become: "{{ docker_compose_user != ansible_user }}"
  become_user: "{{ docker_compose_user }}"
  ansible.builtin.systemd:
    name: "{{ docker_compose_service_name }}.timer"
    scope: user
    daemon_reload: true
    enabled: true
    state: started
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts.getent_passwd[docker_compose_user][1] }}"
