---

- name: Install pyenv build dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ install_pyenv_build_deps }}"
    state: present
    update_cache: true

- name: Look up install_pyenv_user's home dir
  ansible.builtin.getent:
    database: passwd
    key: "{{ install_pyenv_user }}"

- name: Clone pyenv
  become: "{{ install_pyenv_user != ansible_user }}"
  become_user: "{{ install_pyenv_user }}"
  ansible.builtin.git:
    repo: "{{ install_pyenv_repo }}"
    dest: "{{ install_pyenv_root }}"
    update: true

- name: Clone pyenv-virtualenv plugin
  become: "{{ install_pyenv_user != ansible_user }}"
  become_user: "{{ install_pyenv_user }}"
  ansible.builtin.git:
    repo: "{{ install_pyenv_virtualenv_repo }}"
    dest: "{{ install_pyenv_root }}/plugins/pyenv-virtualenv"
    update: true

- name: Add pyenv init block to user's bashrc
  become: "{{ install_pyenv_user != ansible_user }}"
  become_user: "{{ install_pyenv_user }}"
  ansible.builtin.blockinfile:
    path: "{{ ansible_facts.getent_passwd[install_pyenv_user][4] }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init - bash)"
      eval "$(pyenv virtualenv-init -)"
