---

unattended_upgrades_origins:
  - '"origin=Debian,codename=${distro_codename},label=Debian-Security";'

unattended_upgrades_blacklist: []

unattended_upgrades_autofix_interrupted: true
unattended_upgrades_minimal_steps: true
unattended_upgrades_install_on_shutdown: false
unattended_upgrades_mail: ""
unattended_upgrades_mail_report: "on-change"
unattended_upgrades_remove_unused_kernel_packages: true
unattended_upgrades_remove_new_unused_dependencies: true
unattended_upgrades_remove_unused_dependencies: false
unattended_upgrades_automatic_reboot: false
unattended_upgrades_automatic_reboot_with_users: true
unattended_upgrades_automatic_reboot_time: "02:00"

apt_periodic_update_interval: 1
apt_periodic_download_upgradeable: 1
apt_periodic_autoclean_interval: 7
apt_periodic_unattended_upgrade: 1
