- name: Ubuntu Provisioner
  hosts: proxmox
  become: true
  gather_facts: false
  roles:
    - role: mirceanton.proxmox_cloudbuntu
      vars:
        proxmox_cloudbuntu_vmid: 9003
        proxmox_cloudbuntu_name: cloud-deb
        proxmox_cloudbuntu_disk_device: local
        proxmox_cloudbuntu_ci_user: simon
        proxmox_cloudbuntu_ci_pass: test123
        proxmox_cloudbuntu_machine_type: q35
        proxmox_clodubuntu_bios_type: ovmf
        proxmox_cloudbuntu_cpu_type: kvm64
        proxmox_cloudbuntu_disk_size: 30G
        proxmox_cloudbuntu_ci_keys: 
          - "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        proxmox_cloudbuntu_image_link: https://cloud.debian.org/images/cloud/trixie/daily/latest/debian-13-generic-amd64-daily.qcow2
        proxmox_cloudbuntu_image_dest: /var/lib/vz/template/iso/debian-13-generic-amd64-daily.qcow2

      proxmox_cloudbuntu_cpu_cores: 4
      proxmox_cloudbuntu_ram: 4096
    - role: ../../roles/clone_vm
      vars:
        vm_name: vmdeb3
        template_id: 9003
        passthrough_gpu: true
        passthrough_ssd_id: nvme-WDC_WDS480G2G0C-00AJM0_223764448712

    # - role: ../../roles/import_omv
    #   vars:
    #     omv_backup_file: ../../vm-template-backups/vzdump-qemu-101-2023_05_20-14_56_21.vma.zst
    #     omv_template_id: 9005
    # - role: ../../roles/clone_vm
    #   vars:
    #     vm_name: omv
    #     template_id: 9005
    #     passthrough_gpu: false
    #     passthrough_ssd_id: ata-WDC_WD80EDAZ-11TA3A0_VDKJJL9K