---

docker_compose_user: "{{ ansible_user }}"
docker_compose_service_name: docker-compose-up
docker_compose_calendar: "Sat *-*-* 18:00:00"
docker_compose_project_dir: "{{ docker_compose_file | dirname }}"
