---
- name: Get next free VM ID
  ansible.builtin.command: pvesh get /cluster/nextid
  register: vmid
  changed_when: false

- name: Clone VM
  ansible.builtin.command: "qm clone {{ template_id }} {{ vmid.stdout }} --name {{ vm_name }} --full true"

- name: Passthrough GPU
  ansible.builtin.command: "qm set {{ vmid.stdout}} -hostpci0 0000:00:02,pcie=on"